export type {
  CanceledIssue,
  CanceledIssueResolution,
  CompletedIssue,
  CompletedIssueResolution,
  ExtensionMap,
  ExtensionValue,
  Issue,
  IssueResolution,
  IssueSpecVersion,
  IssueStatus,
  NonTerminalIssue,
  NonTerminalIssueStatus,
  Rfc3339Timestamp,
  TerminalIssue,
  TerminalIssueStatus,
} from "./issue.ts";
export type {
  CoreIssueRelation,
  CustomIssueRelation,
  DependencyIssueLink,
  DependencyRequiredBefore,
  IssueLink,
  IssueRef,
  NonDependencyIssueLink,
  NonDependencyIssueRelation,
} from "./link.ts";
